### ISSUE TITLE
Error in the readme.md>installation>pip install retinaface

### ISSUE THREAD

**Issue by Akshit-ls** [jooleer/facesort#1]
https://github.com/jooleer/facesort#installation in this instead of pip install retinaface I think pip install retina-face should be there. Please check. Thanks

**Comment by milliyin** [comment]
Hey! I can help you make this README.md file. Assign this to me.

**Comment by jooleer** [comment]
Issue fixed, thanks for the report @Akshit-ls and the fix @milliyin 🙏
